### ISSUE TITLE
Currency Conversion display issue 

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-android-wallet#13]
There seems to be an issue with the "LOKI" button displayed on the main screen inside the wallet, when pressed the expected behavior should be that a list of alternative currencies should display. when an alternative currency is selected it should replace the "LOKI" button with the ticker of the currency, for example "JPY". At this point the balance of the wallet should be auto converted into the chosen currency.

Right now you press on the Loki button and select the currency you desire but after selection the button immediately goes back to showing the Loki balance again.

**Comment by spacecatpixel** [comment]
![android1](https://user-images.githubusercontent.com/39609800/50808871-b5376d80-1354-11e9-8f41-6e11f88b6b5d.JPG)

**Comment by KeeJef** [comment]
should be able to use the Coingecko API for this example

curl -X GET "https://api.coingecko.com/api/v3/simple/price?ids=loki-network&vs_currencies=AUD" -H "accept: application/json"

you can find the list of supported currencies here https://www.coingecko.com/en/api#
