### ISSUE TITLE
android wallet not syncing 

### ISSUE THREAD

**Issue by cheese666** [loki-project/loki-android-wallet#30]
as of yesterday 3/23/20 it started with syncing 320 blocks, then 425. I left it running all night and this morning it was the same. I closed and re-opened and now it say syncing with 670 blocks. I tried multiple nodes with same results.

**Comment by cheese666** [comment]
still same issue. I can not even restore my wallet on windows or android, will not take my backup file and my seed is 21 words (I have a photo) the new software wants 25. 

When I do sync my wallet it goes to about the block where it forked, 1,700 or so, and then freezes, when I look at my "secret" it give a bunch of technical errors. I am stuck here without a wallet!!!!

**Comment by KeeJef** [comment]
The Android wallet has not yet been upgraded so it cannot sync past the hardfork, we are working on an upgrade now, for now you can use the desktop electron wallet or the CLI wallet if you need to perform transactions, an update should be coming soon

**Comment by cheese666** [comment]
working now thank you.
